# Generated by Django 3.2.5 on 2024-02-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField(blank=True, default=0, null=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('desc', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
