# Generated by Django 3.2.5 on 2024-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
