# Generated by Django 4.1.1 on 2024-02-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0003_category_product_category'),
        ('Search', '0004_rename_ownerid_owner_shopid_owner_shopname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewId', models.IntegerField(default=0, null=True)),
                ('comment', models.CharField(max_length=100, null=True)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Search.customer')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.product')),
            ],
        ),
    ]
