# Generated by Django 5.0.2 on 2024-02-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("address", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("order_no", models.AutoField(primary_key=True, serialize=False)),
                ("order_state", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("product_id", models.AutoField(primary_key=True, serialize=False)),
                ("product_type", models.CharField(max_length=100)),
                ("product_name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("availability", models.BooleanField()),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                ("tracking_id", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horekrokom1.customer",
                    ),
                ),
                (
                    "order_no",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horekrokom1.order",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horekrokom1.product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "customer_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horekrokom1.customer",
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="horekrokom1.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer_id", "product_id")},
            },
        ),
    ]
