# Generated by Django 4.1.1 on 2024-02-22 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0003_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='indorder',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 22), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.date(2024, 2, 22), null=True),
        ),
    ]
