# Generated by Django 4.1.1 on 2024-02-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0005_alter_indorder_date_alter_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='indorder',
            name='status',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
