# Generated by Django 4.1.1 on 2024-02-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cart', '0006_indorder_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
