# Generated by Django 4.1.1 on 2024-02-12 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Search', '0002_customer_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
    ]
