name: Merge to main

on:
  push:
    branches:
      - nayem

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git checkout main
          git merge nayem
          git push origin main
