name: Merge to Main

on:
  push:
    branches:
      - update-nayem

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge branch into main
        run: |
          git config user.email "jucse28.379@gmail.com"
          git config user.name "drzhavoc"
          git fetch origin main:main
          git checkout main
          git merge --no-ff ${{ github.event_name == 'push' && github.ref == 'refs/heads/update-nayem' && github.event.after != '0000000000000000000000000000000000000000' && github.event.before != '0000000000000000000000000000000000000000' ? 'refs/heads/update-nayem' : '' }}
          git push origin main
