name: Merge nayem to main

on:
  push:
    branches:
      - nayem

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge nayem to main
        run: |
          git checkout main
          git merge nayem
          git push origin main
