name: Merge to Main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "jucse28.379@gmail.com"
          git config --global user.name "drzhavoc"

      - name: Check out code
        uses: actions/checkout@v2

      - name: Fetch Nayem branch
        run: git fetch origin nayem:nayem

      - name: Pull main into Nayem branch
        run: |
          git checkout nayem
          git rebase main

      - name: Push changes to Nayem branch
        run: |
          git push origin nayem:nayem

      - name: Merge Nayem branch to Main
        run: |
          git checkout main
          git merge --no-ff nayem
          git push origin main
