name: CI/CD for Django Project

on:
  push:
    branches:
      - nayem

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python environment
        uses: actions/setup-python@v3
        with:
          python-version: '3.x' # Replace with your desired Python version

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test

  merge_to_main:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - uses: actions/checkout@v3

      - name: Check if branch already exists
        run: |
          git fetch origin main
          if git branch --list | grep -q main; then
            echo "Main branch already exists."
          else
            echo "Main branch does not exist. Skipping merge."
            exit 0
          fi

      - name: Create pull request
        uses: actions/github-script@v6
        with:
          script: |
            git checkout nayem
            git config --global user.email "jucse28.379@gmail.com"
            git config --global user.name "drzhavoc"
            git pull origin nayem
            gh pr create --title "Merge nayem branch" --body "Merging changes from nayem branch" --head nayem

      - name: Merge pull request (optional)
        uses: actions/github-script@v6
        with:
          script: |
            if [[ $PR_NUMBER ]]; then
              gh pr merge $PR_NUMBER --auto --squash
            fi
        env:
          PR_NUMBER: ${{ github.event.pull_requests && github.event.pull_requests[0].number }}

