name: Merge to Main

on:
  pull_request:
    branches:
      - nayem
    types:
      - closed

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Merge to main
        run: |
          git config --global user.email "jucse28.379@gmail.com"
          git config --global user.name "drzhavoc"
          git fetch origin main
          git checkout main
          git merge --no-ff ${{ github.event.pull_request.head.ref }}
          git push origin main
