name: Merge to Main

on:
  push:
    branches:
      - update-nayem

jobs:
  merge_to_main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge branch into main
        if: github.ref == 'refs/heads/update-nayem'
        run: |
          git config --global user.email "jucse28.379@gmail.com"
          git config --global user.name "drzhavoc"
          git fetch origin main
          git checkout main
          git merge --no-ff --allow-unrelated-histories update-nayem
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
